import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ha' | 'yo' | 'ig';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'Who We Are',
    'nav.stand': 'Our Stand',
    'nav.membership': 'E-Membership',
    'nav.election': 'Election Center',
    'nav.media': 'Media Room',
    'nav.contact': 'Contact',
    'hero.title': 'The Alternative is Here.',
    'hero.subtitle': 'Good Governance for Nigeria.',
    'hero.description': 'Join the Social Democratic Party in building a Nigeria that works for all - with social justice, true federalism, and youth inclusion.',
    'hero.join': 'Join the Party',
    'hero.donate': 'Donate N500',
    'hero.members': 'Active Members',
    'tracker.title': 'Shadow Government Tracker',
    'tracker.subtitle': 'Real-time economic indicators vs. SDP targets',
    'tracker.live': 'Live Data',
    'tracker.current': 'Current',
    'tracker.target': 'SDP Target',
    'tracker.fix': 'How We\'ll Fix It',
    'wins.title': 'Latest Wins',
    'wins.subtitle': 'See how SDP is making a real difference across Nigeria',
    'wins.achievements': 'Recent Achievements',
    'why.title': 'Why SDP?',
    'why.subtitle': 'Three pillars that guide everything we do',
    'why.values': 'Our Core Values',
    'why.social': 'Social Justice',
    'why.federalism': 'True Federalism',
    'why.youth': 'Youth Inclusion',
    'election.title': 'Next Election',
    'election.subtitle': 'Time remaining to make your voice heard',
    'election.date': 'Election Date',
    'election.days': 'Days',
    'election.hours': 'Hours',
    'election.minutes': 'Minutes',
    'election.seconds': 'Seconds',
    'endorsements.title': 'Endorsements',
    'endorsements.subtitle': 'Respected organizations and individuals who trust SDP to deliver good governance for Nigeria',
    'endorsements.partners': 'Our Partners',
    'footer.find': 'Find Your Ward Chairman',
    'footer.subtitle': 'Connect with SDP leadership in your local area. Get involved at the grassroots level.',
    'action.join': 'Join',
    'action.donate': 'Donate',
    'action.volunteer': 'Volunteer',
    'action.search': 'Search',
    'products.badge': 'Official Merchandise',
    'products.title': 'Support SDP with Official Products',
    'products.subtitle': 'Show your support and help fund our mission with quality SDP merchandise',
    'products.tShirts': 'T-Shirts',
    'products.tShirtsDesc': 'Show your support with our premium quality SDP branded t-shirts. Made with comfortable, durable fabric.',
    'products.corporatePackage': 'Corporate Package',
    'products.corporatePackageDesc': 'Complete corporate branding package for businesses and organizations supporting SDP.',
    'products.crest': 'Crest',
    'products.crestDesc': 'Official SDP party crest - a symbol of unity, progress, and commitment to good governance.',
    'products.buyNow': 'Buy Now',
    'products.footer': 'All proceeds support SDP initiatives and campaigns across Nigeria',
    'hero.trust.verified': 'Verified Political Party',
    'hero.trust.coverage': '36 States + FCT Coverage',
    'hero.trust.transparent': 'Transparent Governance',
    'hero.descriptionText': 'Join the Social Democratic Party in building a Nigeria that works for all - with',
    'hero.descriptionText2': 'social justice',
    'hero.descriptionText3': 'true federalism',
    'hero.descriptionText4': 'and',
    'hero.descriptionText5': 'youth inclusion',
    'donate.title': 'Make a Donation',
    'donate.subtitle': 'Your contribution powers our campaign for good governance in Nigeria.',
    'donate.continue': 'Continue with',
    'donate.step2.title': 'Complete Your Donation',
    'donate.step2.amount': 'Amount:',
    'donate.form.firstName': 'First Name',
    'donate.form.lastName': 'Last Name',
    'donate.form.email': 'Email Address',
    'donate.form.phone': 'Phone Number',
    'donate.form.otherAmount': 'Other Amount',
    'donate.form.required': 'is required',
    'donate.form.emailInvalid': 'Valid email is required',
    'donate.form.phoneInvalid': 'Valid phone number is required',
    'donate.form.back': 'Back',
    'donate.form.pay': 'Pay',
    'donate.form.processing': 'Processing...',
    'donate.form.secure': 'Secure payment powered by Paystack',
    'donate.success.title': 'Thank You!',
    'donate.success.message': 'Your donation has been received successfully.',
    'donate.success.email': 'A confirmation email has been sent to',
    'donate.success.close': 'Close',
    'donate.error.minAmount': 'Minimum donation amount is ₦100',
    'donate.error.loading': 'Payment gateway is loading. Please try again in a moment.',
    'donate.error.failed': 'Payment failed. Please try again.',
    'donate.error.closed': 'Payment window closed. If you completed the payment, you will receive a confirmation email.',
    'footer.pastMembers': 'Past Members',
    'footer.tagline': 'Building a Nigeria that works for all - with social justice, true federalism, and youth inclusion.',
    'footer.quickLinks': 'Quick Links',
    'footer.getInvolved': 'Get Involved',
    'footer.stayUpdated': 'Stay Updated',
    'footer.subscribe': 'Subscribe',
    'footer.subscribed': 'Thanks for subscribing!',
    'footer.emailPlaceholder': 'Your email',
    'footer.copyright': '© 2025 Social Democratic Party (SDP). All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.accessibility': 'Accessibility',
    'footer.joinParty': 'Join the Party',
    'footer.findCandidates': 'Find Candidates',
    'footer.stateChapters': 'State Chapters',
    'wins.category.legislative': 'Legislative',
    'wins.category.agriculture': 'Agriculture',
    'wins.category.humanitarian': 'Humanitarian',
    'wins.date.daysAgo': 'days ago',
    'wins.date.weekAgo': 'week ago',
    'wins.win1.title': 'Senator Wadada Moves Motion',
    'wins.win1.desc': 'Senator Wadada successfully moved a motion for improved healthcare infrastructure in rural areas across Nigeria.',
    'wins.win2.title': 'SDP Nasarawa Distributes Fertilizer',
    'wins.win2.desc': 'SDP Nasarawa chapter distributed free fertilizer to 5,000 farmers to boost agricultural productivity and food security.',
    'wins.win3.title': 'Party Chairman Visits IDP Camp',
    'wins.win3.desc': 'Party Chairman Prince Adebayo visited IDP camps in Borno, providing relief materials, hope, and a vision for the future.',
    'why.social.desc': 'Fighting for equality, fairness, and justice for all Nigerians regardless of background, ethnicity, or social status.',
    'why.federalism.desc': 'Empowering states and local governments for better governance, development, and resource management.',
    'why.youth.desc': 'Giving young Nigerians a voice and platform to shape the future of our nation through active participation.',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.submit': 'Submit',
    'who.title': 'Who We Are',
    'who.subtitle': 'Party Structure & History - A Legacy of Social Democracy',
    'who.about.title': 'About the Social Democratic Party',
    'who.about.text1': 'The Social Democratic Party of Nigeria (SDP) is a',
    'who.about.text1Highlight': 'centre-left political party',
    'who.about.text1Cont': 'in Nigeria. It was created alongside the National Republican Convention by former military president Ibrahim Babangida, as part of a democracy project meant to form two national political parties – one slightly to the left and the other to the right.',
    'who.about.text2': 'During the Nigerian Third Republic, it was seen as a',
    'who.about.text2Highlight': 'moderate party attractive to young radical intellectuals and socialists',
    'who.about.text2Cont': '. Its manifesto advocates for concerted efforts to improve welfare and fight for social justice.',
    'who.history.title': 'Our History',
    'who.history.subtitle': 'A journey from the Third Republic to the present',
    'who.history.1989': 'After 13 prospective parties were banned by the administration of Ibrahim Babangida, some associations decided to re-align. The People\'s Front of Nigeria, People\'s Solidarity Party, and the Nigerian Labor Party emerged to form the core constituency of the new SDP.',
    'who.history.1990': 'Babagana Kingibe was elected party chairman over his rival Mohammed Arzika. Despite the dominance of Northern Nigerians, the party\'s strength lay in the Igbo people in the states of Imo and Anambra.',
    'who.history.1992': 'The party won',
    'who.history.1992Highlight': '57% of Senate seats',
    'who.history.1992Cont': 'and',
    'who.history.1992Highlight2': '53% of House of Representatives seats',
    'who.history.1992Cont2': 'in the National Assembly election, demonstrating significant electoral strength.',
    'who.history.1993': 'M.K.O. Abiola won the primary election in March 1993 under the Option A4 system. Abiola contested the national election, which was unfortunately annulled by Babangida, marking a significant moment in Nigerian democratic history.',
    'who.history.2015': 'A new party emerged in the name of SDP, formed by a coalition of 13 parties. The revived party contested for posts in the 2015 Nigerian general elections, marking the beginning of SDP\'s return to active politics.',
    'who.history.2025': 'Under the leadership of Prince Adebayo, SDP continues to provide credible alternatives to Nigerians, addressing the failings of other parties and offering a platform for social democracy, true federalism, and youth inclusion.',
    'who.structure.title': 'Party Structure',
    'who.structure.subtitle': 'How SDP was formed and organized',
    'who.structure.formation': 'Formation',
    'who.structure.formationDesc': 'Formed by a coalition of People\'s Front of Nigeria, People\'s Solidarity Party, and Nigerian Labor Party after 13 parties were banned in 1989.',
    'who.structure.leadership': 'Leadership',
    'who.structure.leadershipDesc': 'Leadership was mostly dominated by Northern Nigerians, with Babagana Kingibe elected as party chairman in 1990. Party strength lay in Igbo states of Imo and Anambra.',
    'who.structure.financing': 'Financing',
    'who.structure.financingDesc': 'The party was primarily financed by the Nigerian government and wealthy individuals such as Shehu Musa Yar\'Adua, Francis Nzeribe, and M.K.O. Abiola.',
    'who.manifesto.badge': 'Core Principles',
    'who.manifesto.title': 'Original Manifesto',
    'who.manifesto.subtitle': 'The foundational principles that guide SDP\'s vision for Nigeria',
    'who.manifesto.energy': 'Energy',
    'who.manifesto.energyDesc': 'The State supervises energy supply for industrial and social purposes.',
    'who.manifesto.rural': 'Rural Development',
    'who.manifesto.ruralDesc': 'The State commits to reduce rural poverty and rural-urban migrations through support for community organizations and community development.',
    'who.manifesto.mining': 'Mining and Petrochemicals',
    'who.manifesto.miningDesc': 'The State shall ensure responsible and controlled exploitation of mineral resources.',
    'who.manifesto.labor': 'Labor, Employment, and Wages',
    'who.manifesto.laborDesc': 'Labor will be represented in all dealings with the affairs of working people.',
    'who.manifesto.education': 'Education',
    'who.manifesto.educationDesc': 'Work towards free education programs at all levels.',
    'who.manifesto.defense': 'Defense',
    'who.manifesto.defenseDesc': 'Encourage self-reliance, local production, and setting up local armament industries.',
    'who.manifesto.police': 'Police',
    'who.manifesto.policeDesc': 'Change police attitudes to the state, perception of their obligations, and relations with the citizenry.',
    'who.revival.title': 'SDP Revived',
    'who.revival.text1': 'According to Chief Olu Falae, SDP was revived to address the failings of the two prominent Parties (People\'s Democratic Party and All Progressive Congress), and to provide credible alternatives to Nigerians, as the SDP predates both the APC and PDP and has a history of winning elections.',
    'who.revival.text2': 'The revived party was formed by a coalition of 13 parties and contested in the 2015 Nigerian general elections, marking its return to active political participation.',
    'who.platform.title': 'Our Platform',
    'who.platform.text1': 'SDP\'s platform focuses on providing credible alternatives, fighting corruption, and creating an ideological party with structured deliverables. The party aims to unify the Nigerian people and give voice to their aspirations.',
    'who.platform.text2': 'We are committed to opening political space for young Nigerians and reflecting gender sensitivity while standing with people with disabilities.',
    'who.platformObjectives.title': 'Platform Objectives',
    'who.platformObjectives.subtitle': 'Our commitment to Nigeria\'s future',
    'who.platformObjectives.democratic': 'Further Democratic Ideas',
    'who.platformObjectives.democraticDesc': 'Advance the democratic principles and values of the SDP.',
    'who.platformObjectives.thirdPlatform': 'Third Political Platform',
    'who.platformObjectives.thirdPlatformDesc': 'Become the third political platform and attract credible, competent, and dynamic leaders.',
    'who.platformObjectives.corruption': 'Fight Corruption',
    'who.platformObjectives.corruptionDesc': 'Fight corruption and enthrone the rule of law.',
    'who.platformObjectives.patriots': 'Gather Patriots',
    'who.platformObjectives.patriotsDesc': 'Gather patriotic and social democrats who will represent the people.',
    'who.platformObjectives.ideological': 'Ideological Party',
    'who.platformObjectives.ideologicalDesc': 'Recreate an ideological party with structured deliverables.',
    'who.platformObjectives.national': 'National Party',
    'who.platformObjectives.nationalDesc': 'Form a national party with presence across all states.',
    'who.platformObjectives.youth': 'Youth Inclusion',
    'who.platformObjectives.youthDesc': 'Open political space for young Nigerians.',
    'who.platformObjectives.inclusivity': 'Inclusivity',
    'who.platformObjectives.inclusivityDesc': 'Reflect gender sensitivity and stand with people with disability.',
    'who.platformObjectives.unify': 'Unify Nigeria',
    'who.platformObjectives.unifyDesc': 'Unify the Nigerian people and give voice and action to their aspirations and desires.',
    'who.formerMembers.badge': 'Distinguished Alumni',
    'who.formerMembers.title': 'Former Members',
    'who.formerMembers.subtitle': 'SDP has been home to many distinguished political leaders who have shaped Nigeria\'s political landscape. Some later became senior figures in other parties, while others returned to SDP.',
    'who.leadership.title': 'Current Leadership Structure',
    'who.leadership.subtitle': 'The organs that guide SDP today',
    'who.leadership.nwc': 'National Working Committee (NWC)',
    'who.leadership.chairman': 'Prince Adebayo',
    'who.leadership.chairmanTitle': 'National Chairman',
    'who.leadership.chairmanDesc': 'Leading SDP\'s vision for good governance and national development.',
    'who.leadership.secretary': 'Secretary',
    'who.leadership.secretaryTitle': 'National Secretary',
    'who.leadership.secretaryDesc': 'Overseeing party administration and coordination.',
    'who.leadership.nwcMembers': 'NWC Members',
    'who.leadership.nwcMembersTitle': 'Committee Members',
    'who.leadership.nwcMembersDesc': 'Dedicated leaders working for Nigeria\'s progress.',
    'who.leadership.senate': 'Senate Caucus',
    'who.leadership.senatorWadada': 'Senator Wadada',
    'who.leadership.senatorTitle': 'Senator',
    'who.leadership.senatorWadadaDesc': 'Representing the people and championing legislative reforms.',
    'who.leadership.senatorAkwashiki': 'Senator Akwashiki',
    'who.leadership.senatorAkwashikiDesc': 'Advocating for true federalism and grassroots development.',
    'who.leadership.trustees': 'Board of Trustees',
    'who.leadership.trusteesDesc': 'Our Board of Trustees consists of respected elders and leaders who provide stability, institutional memory, and guidance to the party. They represent decades of experience in Nigerian politics and governance.',
    'who.constitution.title': 'Party Constitution',
    'who.constitution.desc': 'Download the official SDP Constitution. This document outlines our party\'s structure, principles, and governance framework. Transparency is key to building trust.',
    'who.constitution.download': 'Download Constitution (PDF)',
    'who.viewAchievements': 'View Achievements',
    'who.expand': 'Expand',
    'who.collapse': 'Collapse'
  },
  ha: {
    'nav.home': 'Gida',
    'nav.about': 'Wanene Muke',
    'nav.stand': 'Matsayinmu',
    'nav.membership': 'Memba ta Intanet',
    'nav.election': 'Cibiyar Zabe',
    'nav.media': 'Dakin Labarai',
    'nav.contact': 'Tuntuɓi',
    'hero.title': 'Madadin Yana Nan.',
    'hero.subtitle': 'Gudanarwa Mai Kyau ga Najeriya.',
    'hero.description': 'Shiga Jam\'iyyar Dimokraɗiyyar Zamantakewa wajen gina Najeriya da za ta yi aiki ga kowa - tare da adalci na zamantakewa, gaskiyar tarayya, da haɗa kan matasa.',
    'hero.join': 'Shiga Jam\'iyya',
    'hero.donate': 'Ba da Goto N500',
    'hero.members': 'Membobi Masu Aiki',
    'tracker.title': 'Mai Bin Gudanarwar Gwamnati',
    'tracker.subtitle': 'Alamomin tattalin arziƙi na lokaci-lokaci da manufofin SDP',
    'tracker.live': 'Bayanan Kai tsaye',
    'tracker.current': 'Na Yanzu',
    'tracker.target': 'Manufar SDP',
    'tracker.fix': 'Yadda Za Mu Gyara',
    'wins.title': 'Nasarori na Ƙarshe',
    'wins.subtitle': 'Dubi yadda SDP ke yin canji mai gaskiya a duk faɗin Najeriya',
    'wins.achievements': 'Nasarori na Kwanan Nan',
    'why.title': 'Me Yasa SDP?',
    'why.subtitle': 'Ginshiƙai uku waɗanda ke jagorantar duk abin da muke yi',
    'why.values': 'Ƙimar Mu',
    'why.social': 'Adalci na Zamantakewa',
    'why.federalism': 'Gaskiyar Tarayya',
    'why.youth': 'Haɗa Kan Matasa',
    'election.title': 'Zaɓe na Gaba',
    'election.subtitle': 'Lokaci da ya rage don bayar da muryar ku',
    'election.date': 'Ranar Zaɓe',
    'election.days': 'Kwanaki',
    'election.hours': 'Sa\'o\'i',
    'election.minutes': 'Mintuna',
    'election.seconds': 'Dakiku',
    'endorsements.title': 'Amincewa',
    'endorsements.subtitle': 'Ƙungiyoyi da mutane masu daraja waɗanda suka amince da SDP don samar da gudanarwa mai kyau ga Najeriya',
    'endorsements.partners': 'Abokan Huldarmu',
    'footer.find': 'Nemo Shugaban Ward ɗin ku',
    'footer.subtitle': 'Haɗu da shugabannin SDP a yankin ku. Shiga cikin matakin ƙasa.',
    'action.join': 'Shiga',
    'action.donate': 'Ba da Goto',
    'action.volunteer': 'Yin Aikin Sa-kai',
    'action.search': 'Nemo',
    'products.badge': 'Kayayyakin Hukuma',
    'products.title': 'Taimaka wa SDP tare da Kayayyakin Hukuma',
    'products.subtitle': 'Nuna goyon bayan ku kuma taimaka wajen ba da kuɗin manufarmu tare da kayayyakin SDP masu inganci',
    'products.tShirts': 'Riguna',
    'products.tShirtsDesc': 'Nuna goyon bayan ku tare da rigunan SDP masu inganci. An yi su da yadi mai dadi, mai ɗorewa.',
    'products.corporatePackage': 'Fakitin Kamfani',
    'products.corporatePackageDesc': 'Cikakken fakitin alamar kamfani don kasuwanci da ƙungiyoyi masu goyon bayan SDP.',
    'products.crest': 'Tambari',
    'products.crestDesc': 'Tambarin jam\'iyyar SDP na hukuma - alama ta haɗin kai, ci gaba, da sadaukarwa ga gudanarwa mai kyau.',
    'products.buyNow': 'Saya Yanzu',
    'products.footer': 'Duk kuɗaɗen da aka samu suna tallafawa shirye-shiryen SDP da yaƙe-yaƙe a duk faɗin Najeriya',
    'hero.trust.verified': 'Jam\'iyya ta Siyasa da Aka Tabbatar',
    'hero.trust.coverage': 'Jihohi 36 + Yankin FCT',
    'hero.trust.transparent': 'Gudanarwa Mai Bayyanawa',
    'hero.descriptionText': 'Shiga Jam\'iyyar Dimokraɗiyyar Zamantakewa wajen gina Najeriya da za ta yi aiki ga kowa - tare da',
    'hero.descriptionText2': 'adalci na zamantakewa',
    'hero.descriptionText3': 'gaskiyar tarayya',
    'hero.descriptionText4': 'da',
    'hero.descriptionText5': 'haɗa kan matasa',
    'donate.title': 'Yi Goto',
    'donate.subtitle': 'Gudummawar ku tana ƙarfafa yaƙin neman zaɓe don gudanarwa mai kyau a Najeriya.',
    'donate.continue': 'Ci gaba da',
    'donate.step2.title': 'Kammala Gudummawar ku',
    'donate.step2.amount': 'Adadin:',
    'donate.form.firstName': 'Sunan Farko',
    'donate.form.lastName': 'Sunan Ƙarshe',
    'donate.form.email': 'Adireshin Imel',
    'donate.form.phone': 'Lambar Wayar',
    'donate.form.otherAmount': 'Wani Adadi',
    'donate.form.required': 'ana buƙata',
    'donate.form.emailInvalid': 'Ana buƙatar adireshin imel mai inganci',
    'donate.form.phoneInvalid': 'Ana buƙatar lambar wayar mai inganci',
    'donate.form.back': 'Baya',
    'donate.form.pay': 'Biya',
    'donate.form.processing': 'Ana Aiki...',
    'donate.form.secure': 'Biyan kuɗi mai aminci ta hanyar Paystack',
    'donate.success.title': 'Na Gode!',
    'donate.success.message': 'An karɓi gudummawar ku cikin nasara.',
    'donate.success.email': 'An aika imel na tabbatarwa zuwa',
    'donate.success.close': 'Rufe',
    'donate.error.minAmount': 'Mafi ƙarancin adadin gudummawa shine ₦100',
    'donate.error.loading': 'Ana lodawa ƙofar biyan kuɗi. Da fatan za a sake gwadawa nan da ɗan lokaci.',
    'donate.error.failed': 'Biyan kuɗi ya gaza. Da fatan za a sake gwadawa.',
    'donate.error.closed': 'An rufe taga biyan kuɗi. Idan kun kammala biyan kuɗi, za ku karɓi imel na tabbatarwa.',
    'footer.pastMembers': 'Membobi na Baya',
    'footer.tagline': 'Gina Najeriya da za ta yi aiki ga kowa - tare da adalci na zamantakewa, gaskiyar tarayya, da haɗa kan matasa.',
    'footer.quickLinks': 'Hanyoyin Hanzari',
    'footer.getInvolved': 'Shiga Ciki',
    'footer.stayUpdated': 'Kasance da Labari',
    'footer.subscribe': 'Yi Biyan Kuɗi',
    'footer.subscribed': 'Na gode don yin biyan kuɗi!',
    'footer.emailPlaceholder': 'Imel ɗin ku',
    'footer.copyright': '© 2025 Jam\'iyyar Dimokraɗiyyar Zamantakewa (SDP). Duk haƙƙoƙi an keɓe su.',
    'footer.privacy': 'Manufar Keɓewa',
    'footer.terms': 'Sharuɗɗan Sabis',
    'footer.accessibility': 'Samun Damar',
    'footer.joinParty': 'Shiga Jam\'iyya',
    'footer.findCandidates': 'Nemo \'Yan Takara',
    'footer.stateChapters': 'Sasannin Jihohi',
    'wins.category.legislative': 'Majalisa',
    'wins.category.agriculture': 'Noma',
    'wins.category.humanitarian': 'Jin Kai',
    'wins.date.daysAgo': 'kwanaki da suka wuce',
    'wins.date.weekAgo': 'mako da ya wuce',
    'wins.win1.title': 'Sanata Wadada Ya Ƙaddamar da Ƙudiri',
    'wins.win1.desc': 'Sanata Wadada ya yi nasara wajen ƙaddamar da ƙudiri don inganta ababen more rayuwa na kiwon lafiya a yankunan karkara a duk faɗin Najeriya.',
    'wins.win2.title': 'SDP Nasarawa Ta Rarraba Takin Noma',
    'wins.win2.desc': 'Sashen SDP na Nasarawa ya rarraba takin noma kyauta ga manoma 5,000 don haɓaka yawan amfanin gona da tsaro na abinci.',
    'wins.win3.title': 'Shugaban Jam\'iyya Ya Ziyarci Sansanin \'Yan Gudun Hijira',
    'wins.win3.desc': 'Shugaban Jam\'iyya Prince Adebayo ya ziyarci sansanonin \'yan gudun hijira a Borno, yana ba da kayan agaji, bege, da hangen nesa na gaba.',
    'why.social.desc': 'Yaƙi don daidaito, adalci, da adalci ga duk \'yan Najeriya ba tare da la\'akari da asali, ƙabila, ko matsayin zamantakewa ba.',
    'why.federalism.desc': 'Ƙarfafa jihohi da gundumomi don gudanarwa mafi kyau, ci gaba, da sarrafa albarkatun ƙasa.',
    'why.youth.desc': 'Baiwa matasan Najeriya murya da dandamali don tsara makomar ƙasarmu ta hanyar shiga cikin ayyuka.',
    'common.loading': 'Ana Lodawa...',
    'common.error': 'Kuskure',
    'common.success': 'Nasara',
    'common.close': 'Rufe',
    'common.cancel': 'Soke',
    'common.save': 'Ajiye',
    'common.delete': 'Share',
    'common.edit': 'Gyara',
    'common.submit': 'Tura',
    'who.title': 'Wanene Muke',
    'who.subtitle': 'Tsarin Jam\'iyya & Tarihi - Gado na Dimokraɗiyyar Zamantakewa',
    'who.about.title': 'Game da Jam\'iyyar Dimokraɗiyyar Zamantakewa',
    'who.about.text1': 'Jam\'iyyar Dimokraɗiyyar Zamantakewa ta Najeriya (SDP) ita ce',
    'who.about.text1Highlight': 'jam\'iyyar siyasa ta tsakiya-hagu',
    'who.about.text1Cont': 'a Najeriya. An kirkiro ta tare da Yarjejeniyar \'Yan Republican ta Ƙasa ta tsohon shugaban soja Ibrahim Babangida, a matsayin wani ɓangare na aikin dimokraɗiyya da aka yi niyya don samar da jam\'iyyun ƙasa biyu – ɗaya ɗan hagu ɗaya kuma ɗan dama.',
    'who.about.text2': 'A lokacin Jamhuriya ta Uku ta Najeriya, an gan ta a matsayin',
    'who.about.text2Highlight': 'jam\'iyya mai matsakaici wacce ke jan hankalin matasa masu ra\'ayin ra\'ayi da masu ra\'ayin zamantakewa',
    'who.about.text2Cont': '. Manufarta tana ba da shawarar ƙoƙari na haɗin gwiwa don inganta jin daɗi da yaƙi don adalci na zamantakewa.',
    'who.history.title': 'Tarihinmu',
    'who.history.subtitle': 'Tafiya daga Jamhuriya ta Uku zuwa yanzu',
    'who.history.1989': 'Bayan an haramta jam\'iyyu 13 da za su kasance ta gwamnatin Ibrahim Babangida, wasu ƙungiyoyi sun yanke shawarar sake daidaitawa. Gaban Jama\'ar Najeriya, Jam\'iyyar Haɗin Kai ta Jama\'a, da Jam\'iyyar Ƙwadago ta Najeriya sun fito don samar da babban yanki na sabuwar SDP.',
    'who.history.1990': 'An zaɓi Babagana Kingibe shugaban jam\'iyya akan abokin hamayyarsa Mohammed Arzika. Duk da rinjayen \'Yan Najeriya na Arewa, ƙarfin jam\'iyya ya kasance a cikin mutanen Igbo a jihohin Imo da Anambra.',
    'who.history.1992': 'Jam\'iyya ta samu',
    'who.history.1992Highlight': 'kashi 57% na kujerun Majalisar Dattawa',
    'who.history.1992Cont': 'da',
    'who.history.1992Highlight2': 'kashi 53% na kujerun Majalisar Wakilai',
    'who.history.1992Cont2': 'a zaɓen Majalisar Ƙasa, wanda ya nuna ƙarfin zaɓe mai mahimmanci.',
    'who.history.1993': 'M.K.O. Abiola ya ci zaɓen farko a watan Maris 1993 a ƙarƙashin tsarin Option A4. Abiola ya yi takara a zaɓen ƙasa, wanda babu tausayi an soke shi ta Babangida, wanda ya zama lokaci mai mahimmanci a tarihin dimokraɗiyya na Najeriya.',
    'who.history.2015': 'Wata sabuwar jam\'iyya ta fito da sunan SDP, wacce ta samo asali daga haɗin gwiwar jam\'iyyu 13. Jam\'iyyar da aka farfado ta yi takara a zaɓen ƙasa na Najeriya na 2015, wanda ya zama farkon komawar SDP zuwa siyasa mai aiki.',
    'who.history.2025': 'Ƙarƙashin jagorancin Prince Adebayo, SDP na ci gaba da ba da madadin gaskiya ga \'Yan Najeriya, yana magance gazawar wasu jam\'iyyu da ba da dandamali don dimokraɗiyyar zamantakewa, gaskiyar tarayya, da haɗa kan matasa.',
    'who.structure.title': 'Tsarin Jam\'iyya',
    'who.structure.subtitle': 'Yadda aka kafa SDP kuma aka tsara ta',
    'who.structure.formation': 'Kafawa',
    'who.structure.formationDesc': 'An kafa ta ta hanyar haɗin gwiwar Gaban Jama\'ar Najeriya, Jam\'iyyar Haɗin Kai ta Jama\'a, da Jam\'iyyar Ƙwadago ta Najeriya bayan an haramta jam\'iyyu 13 a 1989.',
    'who.structure.leadership': 'Jagoranci',
    'who.structure.leadershipDesc': 'Jagoranci ya kasance mafi yawan \'Yan Najeriya na Arewa, tare da zaɓen Babagana Kingibe a matsayin shugaban jam\'iyya a 1990. Ƙarfin jam\'iyya ya kasance a jihohin Igbo na Imo da Anambra.',
    'who.structure.financing': 'Kuɗi',
    'who.structure.financingDesc': 'Jam\'iyya ta fara samun kuɗi daga gwamnatin Najeriya da masu arziki kamar Shehu Musa Yar\'Adua, Francis Nzeribe, da M.K.O. Abiola.',
    'who.manifesto.badge': 'Ka\'idoji na Asali',
    'who.manifesto.title': 'Manufar Asali',
    'who.manifesto.subtitle': 'Ka\'idojin ginshiƙai waɗanda ke jagorantar hangen nesa na SDP ga Najeriya',
    'who.manifesto.energy': 'Makamashi',
    'who.manifesto.energyDesc': 'Jiha tana kula da wadatar makamashi don dalilai na masana\'antu da zamantakewa.',
    'who.manifesto.rural': 'Ci Gaban Karkara',
    'who.manifesto.ruralDesc': 'Jiha ta yi alƙawarin rage talauci na karkara da ƙaura daga karkara zuwa birni ta hanyar tallafawa ƙungiyoyin al\'umma da ci gaban al\'umma.',
    'who.manifesto.mining': 'Hakar Ma\'adinai da Petrochemicals',
    'who.manifesto.miningDesc': 'Jiha za ta tabbatar da amfani da albarkatun ma\'adinai cikin gaskiya da kuma sarrafa su.',
    'who.manifesto.labor': 'Aiki, Aikin Yi, da Albashi',
    'who.manifesto.laborDesc': 'Za a wakilci aiki a duk hulɗa da al\'amuran ma\'aikata.',
    'who.manifesto.education': 'Ilimi',
    'who.manifesto.educationDesc': 'Aiki don shirye-shiryen ilimi kyauta a duk matakan.',
    'who.manifesto.defense': 'Tsaro',
    'who.manifesto.defenseDesc': 'Ƙarfafa dogaro da kai, samarwa na gida, da kafa masana\'antun makamai na gida.',
    'who.manifesto.police': '\'Yan Sanda',
    'who.manifesto.policeDesc': 'Canza halayen \'yan sanda ga jiha, fahimtar wajibai, da dangantaka da \'yan ƙasa.',
    'who.revival.title': 'SDP Ta Farfado',
    'who.revival.text1': 'Bisa ga Chief Olu Falae, an farfado da SDP don magance gazawar jam\'iyyu biyu da suka shahara (Jam\'iyyar Dimokraɗiyyar Jama\'a da Jam\'iyyar Ci Gaba ta Duka), da kuma ba da madadin gaskiya ga \'Yan Najeriya, kamar yadda SDP ta kasance kafin duka APC da PDP kuma tana da tarihin cin zaɓe.',
    'who.revival.text2': 'Jam\'iyyar da aka farfado ta samo asali daga haɗin gwiwar jam\'iyyu 13 kuma ta yi takara a zaɓen ƙasa na Najeriya na 2015, wanda ya zama komawa zuwa shiga siyasa mai aiki.',
    'who.platform.title': 'Dandamalinmu',
    'who.platform.text1': 'Dandamalin SDP yana mai da hankali kan ba da madadin gaskiya, yaƙi da cin hanci da rashawa, da kuma ƙirƙirar jam\'iyya mai ra\'ayi tare da abubuwan da za a cim ma. Jam\'iyya tana nufin haɗa \'Yan Najeriya da ba da murya ga burinsu.',
    'who.platform.text2': 'Muna da niyyar buɗe sararin siyasa ga matasan Najeriya da kuma nuna hankali ga jinsi yayin tsayawa tare da mutanen da ke da nakasa.',
    'who.platformObjectives.title': 'Manufofin Dandamali',
    'who.platformObjectives.subtitle': 'Sadaukarwar mu ga makomar Najeriya',
    'who.platformObjectives.democratic': 'Ƙara Ra\'ayoyin Dimokraɗiyya',
    'who.platformObjectives.democraticDesc': 'Ci gaba da ka\'idoji da ƙimar dimokraɗiyya na SDP.',
    'who.platformObjectives.thirdPlatform': 'Dandamali na Uku na Siyasa',
    'who.platformObjectives.thirdPlatformDesc': 'Zama dandamali na uku na siyasa kuma jawo shugabanni masu gaskiya, ƙwarewa, da kuzari.',
    'who.platformObjectives.corruption': 'Yaƙi da Cin Hanci',
    'who.platformObjectives.corruptionDesc': 'Yaƙi da cin hanci da kuma kafa dokar doka.',
    'who.platformObjectives.patriots': 'Tattara Masu Kare Ƙasa',
    'who.platformObjectives.patriotsDesc': 'Tattara masu kare ƙasa da dimokraɗiyya na zamantakewa waɗanda za su wakilci mutane.',
    'who.platformObjectives.ideological': 'Jam\'iyya mai Ra\'ayi',
    'who.platformObjectives.ideologicalDesc': 'Sake ƙirƙirar jam\'iyya mai ra\'ayi tare da abubuwan da za a cim ma.',
    'who.platformObjectives.national': 'Jam\'iyya ta Ƙasa',
    'who.platformObjectives.nationalDesc': 'Kafa jam\'iyya ta ƙasa tare da kasancewa a duk jihohi.',
    'who.platformObjectives.youth': 'Haɗa Kan Matasa',
    'who.platformObjectives.youthDesc': 'Buɗe sararin siyasa ga matasan Najeriya.',
    'who.platformObjectives.inclusivity': 'Haɗa Kowa',
    'who.platformObjectives.inclusivityDesc': 'Nuna hankali ga jinsi kuma tsayawa tare da mutanen da ke da nakasa.',
    'who.platformObjectives.unify': 'Haɗa Najeriya',
    'who.platformObjectives.unifyDesc': 'Haɗa \'Yan Najeriya da ba da murya da aiki ga burinsu da sha\'awarsu.',
    'who.formerMembers.badge': 'Tsofaffin Memba Masu Daraja',
    'who.formerMembers.title': 'Tsofaffin Memba',
    'who.formerMembers.subtitle': 'SDP ta kasance gida ga shugabannin siyasa da yawa masu daraja waɗanda suka tsara yanayin siyasa na Najeriya. Wasu daga baya sun zama manyan mutane a wasu jam\'iyyu, yayin da wasu suka koma SDP.',
    'who.leadership.title': 'Tsarin Jagoranci na Yanzu',
    'who.leadership.subtitle': 'Gabobin da ke jagorantar SDP a yau',
    'who.leadership.nwc': 'Kwamitin Aiki na Ƙasa (NWC)',
    'who.leadership.chairman': 'Prince Adebayo',
    'who.leadership.chairmanTitle': 'Shugaban Ƙasa',
    'who.leadership.chairmanDesc': 'Jagorantar hangen nesa na SDP don gudanarwa mai kyau da ci gaban ƙasa.',
    'who.leadership.secretary': 'Sakatare',
    'who.leadership.secretaryTitle': 'Sakataren Ƙasa',
    'who.leadership.secretaryDesc': 'Kula da gudanarwa da daidaitawa na jam\'iyya.',
    'who.leadership.nwcMembers': 'Membobin NWC',
    'who.leadership.nwcMembersTitle': 'Membobin Kwamiti',
    'who.leadership.nwcMembersDesc': 'Shugabanni masu sadaukarwa waɗanda ke aiki don ci gaban Najeriya.',
    'who.leadership.senate': 'Majalisar Dattawa',
    'who.leadership.senatorWadada': 'Sanata Wadada',
    'who.leadership.senatorTitle': 'Sanata',
    'who.leadership.senatorWadadaDesc': 'Wakiltar mutane da kuma yaƙi don gyare-gyare na majalisa.',
    'who.leadership.senatorAkwashiki': 'Sanata Akwashiki',
    'who.leadership.senatorAkwashikiDesc': 'Yaƙi don gaskiyar tarayya da ci gaban ƙasa.',
    'who.leadership.trustees': 'Hukumar Amintattu',
    'who.leadership.trusteesDesc': 'Hukumar Amintattun mu ta ƙunshi manya da shugabanni masu daraja waɗanda ke ba da kwanciyar hankali, ƙwaƙwalwar cibiya, da jagora ga jam\'iyya. Suna wakiltar gogewar shekaru da yawa a siyasa da gudanarwa na Najeriya.',
    'who.constitution.title': 'Kundin Tsarin Mulki na Jam\'iyya',
    'who.constitution.desc': 'Zazzage Kundin Tsarin Mulki na SDP na hukuma. Wannan takarda tana bayyana tsarin jam\'iyyarmu, ka\'idoji, da tsarin gudanarwa. Bayyanawa shine mabuɗin gina aminci.',
    'who.constitution.download': 'Zazzage Kundin Tsarin Mulki (PDF)',
    'who.viewAchievements': 'Dubi Nasarori',
    'who.expand': 'Faɗaɗa',
    'who.collapse': 'Rufe'
  },
  yo: {
    'nav.home': 'Ile',
    'nav.about': 'Ta ni Wa',
    'nav.stand': 'Ipo Wa',
    'nav.membership': 'Igbeyawo E-',
    'nav.election': 'Ile-Idibo',
    'nav.media': 'Ile Iroyin',
    'nav.contact': 'Kan si',
    'hero.title': 'Eyi ti wa ni.',
    'hero.subtitle': 'Ijoba Dara fun Naijiria.',
    'hero.description': 'Darapo si Egbe Awon Oloselu Alawujo lati kọ Naijiria ti o n ṣiṣẹ fun gbogbo eniyan - pẹlu oju-ọjọ alawujo, ijọba ti o tọ, ati ifikun awon ọdọ.',
    'hero.join': 'Darapo si Egbe',
    'hero.donate': 'Fi N500',
    'hero.members': 'Awọn Memba Ti Nṣiṣẹ',
    'tracker.title': 'Oluwo Ijoba Oji',
    'tracker.subtitle': 'Awọn aami iṣowo ni igba ati awọn ibi-ọrọ SDP',
    'tracker.live': 'Data Ni Igba',
    'tracker.current': 'Lọwọlọwọ',
    'tracker.target': 'Ibi-ọrọ SDP',
    'tracker.fix': 'Bawo Ni A O Ṣe Atunṣe',
    'wins.title': 'Awọn Isegun Kẹhin',
    'wins.subtitle': 'Wo bi SDP ṣe n ṣe iyipada gidi ni gbogbo agbegbe Naijiria',
    'wins.achievements': 'Awọn Isegun Ti O Ṣe Aiyipada',
    'why.title': 'Kí ni idi SDP?',
    'why.subtitle': 'Awọn opo mẹta ti o fi itọsọna ohun gbogbo ti a n ṣe',
    'why.values': 'Awọn Iye Pataki Wa',
    'why.social': 'Oju-ọjọ Alawujo',
    'why.federalism': 'Ijọba Ti O Tọ',
    'why.youth': 'Ifikun Awọn Ọdọ',
    'election.title': 'Idibo Ti O Nbo',
    'election.subtitle': 'Aago ti o ku lati fi ohun rẹ gbọ',
    'election.date': 'Ọjọ Idibo',
    'election.days': 'Ọjọ',
    'election.hours': 'Wakati',
    'election.minutes': 'Iṣẹju',
    'election.seconds': 'Iṣẹju Aaya',
    'endorsements.title': 'Ifọwọsi',
    'endorsements.subtitle': 'Awọn ẹgbẹ ati awọn eniyan ti o ni ẹtẹ ti o gbẹkẹle SDP lati pese ijọba dara fun Naijiria',
    'endorsements.partners': 'Awọn Alabaṣepọ Wa',
    'footer.find': 'Wa Oluwo Ward Rẹ',
    'footer.subtitle': 'Kan si awọn oludari SDP ni agbegbe rẹ. Darapo si ipele ti o ga.',
    'action.join': 'Darapo',
    'action.donate': 'Fi',
    'action.volunteer': 'Ṣe Iṣẹ Afẹfẹ',
    'action.search': 'Wa',
    'products.badge': 'Awọn Ohun Elo Ofisiali',
    'products.title': 'Ṣe Atilẹyin SDP Pẹlu Awọn Ọja Ofisiali',
    'products.subtitle': 'Fi atilẹyin rẹ hàn ki o si ran wa lọwọ lati fi owo ọrọ wa pẹlu awọn ọja SDP ti o dara',
    'products.tShirts': 'Awọn Shirt T-',
    'products.tShirtsDesc': 'Fi atilẹyin rẹ hàn pẹlu awọn shirt T- SDP ti o dara. A ṣe pẹlu asọ ti o dara, ti o le duro.',
    'products.corporatePackage': 'Apoti Ijọba',
    'products.corporatePackageDesc': 'Apoti aami ijọba ni kikun fun awọn iṣowo ati awọn ẹgbẹ ti o n ṣe atilẹyin SDP.',
    'products.crest': 'Aami',
    'products.crestDesc': 'Aami egbe SDP ofisiali - aami ti iṣọkan, ilọsiwaju, ati ifojusi ijọba dara.',
    'products.buyNow': 'Ra Ni Bayi',
    'products.footer': 'Gbogbo owo ti o jade n ṣe atilẹyin awọn ipolongo SDP ati awọn ipolongo ni gbogbo agbegbe Naijiria',
    'hero.trust.verified': 'Egbe Oloselu Ti A Fi Idi Mule',
    'hero.trust.coverage': 'Awọn Ipinle 36 + Agbegbe FCT',
    'hero.trust.transparent': 'Ijọba Ti O Ṣe Afihan',
    'hero.descriptionText': 'Darapo si Egbe Awon Oloselu Alawujo lati kọ Naijiria ti o n ṣiṣẹ fun gbogbo eniyan - pẹlu',
    'hero.descriptionText2': 'oju-ọjọ alawujo',
    'hero.descriptionText3': 'ijọba ti o tọ',
    'hero.descriptionText4': 'ati',
    'hero.descriptionText5': 'ifikun awon ọdọ',
    'donate.title': 'Ṣe Ifowosipele',
    'donate.subtitle': 'Ifowosipele rẹ n ṣe agbara ipolongo wa fun ijọba dara ni Naijiria.',
    'donate.continue': 'Tẹsiwaju pẹlu',
    'donate.step2.title': 'Parẹ Ifowosipele Rẹ',
    'donate.step2.amount': 'Iye:',
    'donate.form.firstName': 'Orukọ Akọkọ',
    'donate.form.lastName': 'Orukọ Ikẹhin',
    'donate.form.email': 'Adirẹsi Imẹli',
    'donate.form.phone': 'Nọmba Foonu',
    'donate.form.otherAmount': 'Iye Miiran',
    'donate.form.required': 'jẹ dandan',
    'donate.form.emailInvalid': 'Adirẹsi imẹli ti o tọ jẹ dandan',
    'donate.form.phoneInvalid': 'Nọmba foonu ti o tọ jẹ dandan',
    'donate.form.back': 'Padà',
    'donate.form.pay': 'Sanwo',
    'donate.form.processing': 'N ṣiṣẹ...',
    'donate.form.secure': 'Isanwo aabo ti Paystack ṣe agbara',
    'donate.success.title': 'O Ṣeun!',
    'donate.success.message': 'A ti gba ifowosipele rẹ ni aṣeyọri.',
    'donate.success.email': 'A ti fi imẹli ijẹrisi ranṣẹ si',
    'donate.success.close': 'Pa',
    'donate.error.minAmount': 'Iye ifowosipele ti o kere jẹ ₦100',
    'donate.error.loading': 'Ẹnu-ọna isanwo n gba. Jọwọ gbiyanju lẹẹkansi ni akoko diẹ.',
    'donate.error.failed': 'Isanwo kuna. Jọwọ gbiyanju lẹẹkansi.',
    'donate.error.closed': 'A ti pa fẹrẹẹ isanwo. Ti o ba parẹ isanwo, o yoo gba imẹli ijẹrisi.',
    'footer.pastMembers': 'Awọn Memba Ti Kọja',
    'footer.tagline': 'Kọ Naijiria ti o n ṣiṣẹ fun gbogbo eniyan - pẹlu oju-ọjọ alawujo, ijọba ti o tọ, ati ifikun awọn ọdọ.',
    'footer.quickLinks': 'Awọn Ọna Kẹkẹ',
    'footer.getInvolved': 'Darapo',
    'footer.stayUpdated': 'Tọju Imọ',
    'footer.subscribe': 'Forukọsilẹ',
    'footer.subscribed': 'O ṣeun fun forukọsilẹ!',
    'footer.emailPlaceholder': 'Imẹli rẹ',
    'footer.copyright': '© 2025 Egbe Awon Oloselu Alawujo (SDP). Gbogbo ẹtọ wa ni.',
    'footer.privacy': 'Eto Ikọkọ',
    'footer.terms': 'Awọn Ofin Iṣẹ',
    'footer.accessibility': 'Wiwọle',
    'footer.joinParty': 'Darapo si Egbe',
    'footer.findCandidates': 'Wa Awọn Oludije',
    'footer.stateChapters': 'Awọn Ọrọ Ipinle',
    'wins.category.legislative': 'Ofin',
    'wins.category.agriculture': 'Agbe',
    'wins.category.humanitarian': 'Eniyan',
    'wins.date.daysAgo': 'ọjọ sẹhin',
    'wins.date.weekAgo': 'ọsẹ kan sẹhin',
    'wins.win1.title': 'Senator Wadada Gbe Igbekale',
    'wins.win1.desc': 'Senator Wadada ni aṣeyọri gbe igbekale fun awọn ohun elo ilera ti o dara ni awọn agbegbe ile ni gbogbo agbegbe Naijiria.',
    'wins.win2.title': 'SDP Nasarawa Pin Awọn Oje',
    'wins.win2.desc': 'Ẹka SDP Nasarawa pin awọn oje ọfẹ si awọn agbe 5,000 lati mu iṣelọpọ agbe ati aabo ounje pọ si.',
    'wins.win3.title': 'Alaga Egbe Ṣe Ayẹwo Agbegbe IDP',
    'wins.win3.desc': 'Alaga Egbe Prince Adebayo ṣe ayẹwo awọn agbegbe IDP ni Borno, pese awọn ohun iranlọwọ, ireti, ati iran ti o n bọ.',
    'why.social.desc': 'Jija fun idogba, oju-ọjọ, ati oju-ọjọ fun gbogbo awọn eniyan Naijiria laisi wo ipilẹ, ẹya, tabi ipo awujọ.',
    'why.federalism.desc': 'Mu awọn ipinle ati awọn ijọba agbegbe agbara fun ijọba ti o dara, ilọsiwaju, ati iṣakoso awọn ohun-ini.',
    'why.youth.desc': 'Fun awọn ọdọ Naijiria ohun ati pẹpẹ lati ṣe ọna ọjọ-ọjọ orilẹ-ede wa nipasẹ ifarahan ti o n ṣiṣẹ.',
    'common.loading': 'N Gba...',
    'common.error': 'Aṣiṣe',
    'common.success': 'Aṣeyọri',
    'common.close': 'Pa',
    'common.cancel': 'Fagilee',
    'common.save': 'Fi pamọ',
    'common.delete': 'Paarẹ',
    'common.edit': 'Ṣatunkọ',
    'common.submit': 'Fi ranṣẹ',
    'who.title': 'Ta ni Wa',
    'who.subtitle': 'Ile-ẹgbẹ & Itan - Ọgbọn ti Awọn Oloselu Alawujo',
    'who.about.title': 'Nipa Egbe Awon Oloselu Alawujo',
    'who.about.text1': 'Egbe Awon Oloselu Alawujo ti Naijiria (SDP) jẹ',
    'who.about.text1Highlight': 'egbe oloselu aarin-osì',
    'who.about.text1Cont': 'ni Naijiria. A ṣe pẹlu Igbimọ Apejọ Ọmọ Orilẹ-ede nipasẹ aare soja tẹlẹ Ibrahim Babangida, gẹgẹbi apakan iṣẹ ijọba ti a pese lati ṣe awọn egbe oloselu orilẹ-ede meji – ọkan diẹ si osi ati ọkan si ọtun.',
    'who.about.text2': 'Ni akoko Ijọba Kẹta ti Naijiria, a rii rẹ gẹgẹbi',
    'who.about.text2Highlight': 'egbe ti o dara ti o n fa awọn ọmọde ti o ni imọran ati awọn oloselu alawujo',
    'who.about.text2Cont': '. Awọn ọrọ rẹ n ṣe akiyesi fun awọn igbiyanju pẹlu lati mu ilera ati ja fun oju-ọjọ alawujo.',
    'who.history.title': 'Itan Wa',
    'who.history.subtitle': 'Irìn-ajo lati Ijọba Kẹta de lọwọlọwọ',
    'who.history.1989': 'Lẹhin ti a ti kọ awọn egbe 13 ti o n bọ nipasẹ ijọba Ibrahim Babangida, awọn ẹgbẹ kan pinnu lati tun ṣe. Gbangba Awọn Eniyan Naijiria, Egbe Alawujo Awọn Eniyan, ati Egbe Awọn Oṣiṣẹ Naijiria jẹ wọle lati ṣe agbegbe pataki ti SDP tuntun.',
    'who.history.1990': 'A yan Babagana Kingibe gẹgẹbi alaga egbe lori ota rẹ Mohammed Arzika. Ni kikọ ti Awọn Eniyan Naijiria Ariwa, agbara egbe wa ni awọn eniyan Igbo ni awọn ipinle Imo ati Anambra.',
    'who.history.1992': 'Egbe gba',
    'who.history.1992Highlight': '57% awọn ijoko Majẹmu',
    'who.history.1992Cont': 'ati',
    'who.history.1992Highlight2': '53% awọn ijoko Ile Awọn Aṣoju',
    'who.history.1992Cont2': 'ni idibo Ile-igbimọ Orilẹ-ede, ti o fi agbara idibo to ṣe pataki hàn.',
    'who.history.1993': 'M.K.O. Abiola gba idibo akọkọ ni Oṣu Kẹta 1993 labẹ eto Option A4. Abiola ṣe idibo orilẹ-ede, eyiti o jẹ aṣiṣe ti Babangida pa, ti o jẹ akoko pataki ni itan ijọba Naijiria.',
    'who.history.2015': 'Egbe tuntun kan jẹ wọle ni orukọ SDP, ti a ṣe pẹlu apapọ awọn egbe 13. Egbe ti a tun ṣe ṣe idibo fun awọn ipo ni idibo orilẹ-ede Naijiria 2015, ti o jẹ ibẹrẹ ti SDP pada si oloselu ti o n ṣiṣẹ.',
    'who.history.2025': 'Labẹ iṣakoso Prince Adebayo, SDP n tẹsiwaju lati pese awọn aṣayan gidi si awọn eniyan Naijiria, ṣiṣe awọn aṣiṣe awọn egbe miiran ati pese pẹpẹ fun oloselu alawujo, ijọba ti o tọ, ati ifikun awọn ọdọ.',
    'who.structure.title': 'Ile-ẹgbẹ Egbe',
    'who.structure.subtitle': 'Bawo ni a ṣe ṣe SDP ati ṣeto rẹ',
    'who.structure.formation': 'Iṣẹda',
    'who.structure.formationDesc': 'A ṣe pẹlu apapọ Gbangba Awọn Eniyan Naijiria, Egbe Alawujo Awọn Eniyan, ati Egbe Awọn Oṣiṣẹ Naijiria lẹhin ti a ti kọ awọn egbe 13 ni 1989.',
    'who.structure.leadership': 'Iṣakoso',
    'who.structure.leadershipDesc': 'Iṣakoso jẹ mọjuba nipasẹ Awọn Eniyan Naijiria Ariwa, pẹlu yiyan Babagana Kingibe gẹgẹbi alaga egbe ni 1990. Agbara egbe wa ni awọn ipinle Igbo ti Imo ati Anambra.',
    'who.structure.financing': 'Owo',
    'who.structure.financingDesc': 'Egbe jẹ owo akọkọ nipasẹ ijọba Naijiria ati awọn eniyan ọlọrọ bii Shehu Musa Yar\'Adua, Francis Nzeribe, ati M.K.O. Abiola.',
    'who.manifesto.badge': 'Awọn Ọna Pataki',
    'who.manifesto.title': 'Awọn Ọrọ Akọkọ',
    'who.manifesto.subtitle': 'Awọn ọna ginshiƙai ti o fi itọsọna iran SDP fun Naijiria',
    'who.manifesto.energy': 'Agbara',
    'who.manifesto.energyDesc': 'Ipinle n ṣe abojuto pese agbara fun awọn idi ile-iṣẹ ati awujọ.',
    'who.manifesto.rural': 'Ilọsiwaju Ile',
    'who.manifesto.ruralDesc': 'Ipinle n ṣe akiyesi lati dinku osi ile ati iyipada lati ile si ilu nipasẹ atilẹyin fun awọn ẹgbẹ agbegbe ati ilọsiwaju agbegbe.',
    'who.manifesto.mining': 'Iwakiri ati Petrochemicals',
    'who.manifesto.miningDesc': 'Ipinle yoo rii daju iwulo ati iṣakoso ti awọn ohun-ini mineral.',
    'who.manifesto.labor': 'Iṣẹ, Iṣẹ, ati Owo-ori',
    'who.manifesto.laborDesc': 'Iṣẹ yoo jẹ wakilẹ ni gbogbo iṣẹ pẹlu awọn iṣẹ awọn eniyan ti o n ṣiṣẹ.',
    'who.manifesto.education': 'Ẹkọ',
    'who.manifesto.educationDesc': 'Ṣiṣẹ si awọn eto ẹkọ ọfẹ ni gbogbo awọn ipele.',
    'who.manifesto.defense': 'Aabo',
    'who.manifesto.defenseDesc': 'Mu igbẹkẹle ara, iṣelọpọ agbegbe, ati ṣeto awọn ile-iṣẹ agbegbe.',
    'who.manifesto.police': 'Ọlọpa',
    'who.manifesto.policeDesc': 'Yipada awọn iwa ọlọpa si ipinle, oju-ọjọ awọn iṣẹ wọn, ati ibatan pẹlu awọn ọmọ orilẹ-ede.',
    'who.revival.title': 'SDP Ti Tun Ṣe',
    'who.revival.text1': 'Gẹgẹbi Chief Olu Falae, a tun ṣe SDP lati ṣe awọn aṣiṣe awọn Egbe meji ti o ṣe pataki (Egbe Awọn Oloselu Awọn Eniyan ati Gbogbo Egbe Oloselu Oloselu), ati lati pese awọn aṣayan gidi si awọn eniyan Naijiria, gẹgẹbi SDP ṣe ṣe ṣaaju awọn mejeeji APC ati PDP ati ni itan ti gba awọn idibo.',
    'who.revival.text2': 'Egbe ti a tun ṣe ṣe pẹlu apapọ awọn egbe 13 ati ṣe idibo fun awọn ipo ni idibo orilẹ-ede Naijiria 2015, ti o jẹ pada si ipa oloselu ti o n ṣiṣẹ.',
    'who.platform.title': 'Pẹpẹ Wa',
    'who.platform.text1': 'Pẹpẹ SDP n ṣe akiyesi si pese awọn aṣayan gidi, ja fun iwa-ipa, ati ṣẹda egbe ọrọ pẹlu awọn ohun ti o ṣeto. Egbe n ṣe akiyesi lati ṣe awọn eniyan Naijiria ati fun ni ohun si awọn ireti wọn.',
    'who.platform.text2': 'A n ṣe akiyesi lati ṣii aaye oloselu fun awọn ọdọ Naijiria ati ṣe akiyesi iwa-ipa ọkunrin-obinrin pẹlu duro pẹlu awọn eniyan ti o ni ailera.',
    'who.platformObjectives.title': 'Awọn Ibi-ọrọ Pẹpẹ',
    'who.platformObjectives.subtitle': 'Ifojusi wa si ọjọ-ọjọ Naijiria',
    'who.platformObjectives.democratic': 'Ṣe Awọn Ọrọ Ijọba Siwaju',
    'who.platformObjectives.democraticDesc': 'Ṣe awọn ọna ati awọn iye ti ijọba SDP siwaju.',
    'who.platformObjectives.thirdPlatform': 'Pẹpẹ Oloselu Kẹta',
    'who.platformObjectives.thirdPlatformDesc': 'Di pẹpẹ oloselu kẹta ati fa awọn oludari gidi, ti o tọ, ati ti o n ṣiṣẹ.',
    'who.platformObjectives.corruption': 'Ja fun Iwa-ipa',
    'who.platformObjectives.corruptionDesc': 'Ja fun iwa-ipa ati ṣe ofin ti ofin.',
    'who.platformObjectives.patriots': 'Gba Awọn Olukọlẹ',
    'who.platformObjectives.patriotsDesc': 'Gba awọn olukọlẹ ati awọn oloselu alawujo ti yoo wakilẹ awọn eniyan.',
    'who.platformObjectives.ideological': 'Egbe Ọrọ',
    'who.platformObjectives.ideologicalDesc': 'Tun ṣẹda egbe ọrọ pẹlu awọn ohun ti o ṣeto.',
    'who.platformObjectives.national': 'Egbe Orilẹ-ede',
    'who.platformObjectives.nationalDesc': 'Ṣe egbe orilẹ-ede pẹlu iwọle ni gbogbo awọn ipinle.',
    'who.platformObjectives.youth': 'Ifikun Awọn Ọdọ',
    'who.platformObjectives.youthDesc': 'Ṣii aaye oloselu fun awọn ọdọ Naijiria.',
    'who.platformObjectives.inclusivity': 'Ifikun',
    'who.platformObjectives.inclusivityDesc': 'Ṣe akiyesi iwa-ipa ọkunrin-obinrin ati duro pẹlu awọn eniyan ti o ni ailera.',
    'who.platformObjectives.unify': 'Ṣe Naijiria',
    'who.platformObjectives.unifyDesc': 'Ṣe awọn eniyan Naijiria ati fun ni ohun ati iṣẹ si awọn ireti ati awọn ifẹ wọn.',
    'who.formerMembers.badge': 'Awọn Memba Ti Kọja Ti O Ni Ẹtẹ',
    'who.formerMembers.title': 'Awọn Memba Ti Kọja',
    'who.formerMembers.subtitle': 'SDP ti jẹ ile fun ọpọlọpọ awọn oludari oloselu ti o ni ẹtẹ ti o ti ṣe ayẹwo ayẹwo oloselu Naijiria. Awọn kan lẹhinna di awọn ẹni pataki ni awọn egbe miiran, lakoko ti awọn miiran pada si SDP.',
    'who.leadership.title': 'Ile-ẹgbẹ Iṣakoso Lọwọlọwọ',
    'who.leadership.subtitle': 'Awọn ẹya ti o fi itọsọna SDP loni',
    'who.leadership.nwc': 'Igbimọ Iṣẹ Orilẹ-ede (NWC)',
    'who.leadership.chairman': 'Prince Adebayo',
    'who.leadership.chairmanTitle': 'Alaga Orilẹ-ede',
    'who.leadership.chairmanDesc': 'Fi itọsọna iran SDP fun ijọba dara ati ilọsiwaju orilẹ-ede.',
    'who.leadership.secretary': 'Sakatari',
    'who.leadership.secretaryTitle': 'Sakatari Orilẹ-ede',
    'who.leadership.secretaryDesc': 'Ṣe abojuto ijọba egbe ati iṣakoso.',
    'who.leadership.nwcMembers': 'Awọn Memba NWC',
    'who.leadership.nwcMembersTitle': 'Awọn Memba Igbimọ',
    'who.leadership.nwcMembersDesc': 'Awọn oludari ti o n ṣe akiyesi ti o n ṣiṣẹ fun ilọsiwaju Naijiria.',
    'who.leadership.senate': 'Igbimọ Majẹmu',
    'who.leadership.senatorWadada': 'Senator Wadada',
    'who.leadership.senatorTitle': 'Senator',
    'who.leadership.senatorWadadaDesc': 'Wakilẹ awọn eniyan ati ja fun awọn ayipada ofin.',
    'who.leadership.senatorAkwashiki': 'Senator Akwashiki',
    'who.leadership.senatorAkwashikiDesc': 'Ja fun ijọba ti o tọ ati ilọsiwaju agbegbe.',
    'who.leadership.trustees': 'Igbimọ Awọn Amintattun',
    'who.leadership.trusteesDesc': 'Igbimọ Awọn Amintattun wa pẹlu awọn agba ati awọn oludari ti o ni ẹtẹ ti o pese iduro, ẹkọ ile-iṣẹ, ati itọsọna si egbe. Wọn wakilẹ ọpọlọpọ ọdun iriri ni oloselu Naijiria ati ijọba.',
    'who.constitution.title': 'Ile-ẹgbẹ Egbe',
    'who.constitution.desc': 'Ṣe igbasilẹ Ile-ẹgbẹ SDP ofisiali. Iwe yii ṣe afihan ile-ẹgbẹ egbe wa, awọn ọna, ati eto ijọba. Iṣafihan jẹ bọtini lati kọ igbẹkẹle.',
    'who.constitution.download': 'Ṣe igbasilẹ Ile-ẹgbẹ (PDF)',
    'who.viewAchievements': 'Wo Awọn Isegun',
    'who.expand': 'Fa',
    'who.collapse': 'Dinku'
  },
  ig: {
    'nav.home': 'Ụlọ',
    'nav.about': 'Onye Anyị Bụ',
    'nav.stand': 'Ebe Anyị',
    'nav.membership': 'Ndị otu E-',
    'nav.election': 'Ebe Ntuli Aka',
    'nav.media': 'Ụlọ Mgbasa Ozi',
    'nav.contact': 'Kpọtụrụ',
    'hero.title': 'Nhọrọ Ọzọ Dị Ebe A.',
    'hero.subtitle': 'Ọchịchị Ọma Maka Naịjirịa.',
    'hero.description': 'Sonye na Social Democratic Party n\'ịwulite Naịjirịa nke ga-arụ ọrụ maka mmadụ niile - yana ikpe ziri ezi nke ọha, ezi ọchịchị gọọmentị, na nsonye ndị ntorobịa.',
    'hero.join': 'Sonye na Party',
    'hero.donate': 'Nye N500',
    'hero.members': 'Ndị Otu Na-arụ Ọrụ',
    'tracker.title': 'Ihe Nleba Gọọmentị Onyinyo',
    'tracker.subtitle': 'Ihe ngosi akụ na ụba n\'oge na ebumnuche SDP',
    'tracker.live': 'Data Na-aga n\'ihu',
    'tracker.current': 'Ugbu A',
    'tracker.target': 'Ebumnuche SDP',
    'tracker.fix': 'Otu Anyị Ga-esi Dozie Ya',
    'wins.title': 'Mmeri Kachasị',
    'wins.subtitle': 'Hụ otu SDP si eme mgbanwe dị mkpa n\'ofe Naịjirịa',
    'wins.achievements': 'Mmeri Na-adịbeghị Anya',
    'why.title': 'Gịnị Kpatara SDP?',
    'why.subtitle': 'Ogidi atọ na-eduzi ihe niile anyị na-eme',
    'why.values': 'Ụkpụrụ Anyị',
    'why.social': 'Ikpe Ziri Ezi Ọha',
    'why.federalism': 'Ezi Ọchịchị Gọọmentị',
    'why.youth': 'Nsonye Ndị Ntorobịa',
    'election.title': 'Ntuli Aka Na-esote',
    'election.subtitle': 'Oge fọdụrụ iji mee ka a nụ olu gị',
    'election.date': 'Ụbọchị Ntuli Aka',
    'election.days': 'Ụbọchị',
    'election.hours': 'Awa',
    'election.minutes': 'Nkeji',
    'election.seconds': 'Sekọnd',
    'endorsements.title': 'Nkwado',
    'endorsements.subtitle': 'Ndị otu na ndị mmadụ a na-asọpụrụ tụkwasịrị obi SDP iji nye ọchịchị dị mma maka Naịjirịa',
    'endorsements.partners': 'Ndị Mmekọ Anyị',
    'footer.find': 'Chọta Onye Isi Ward Gị',
    'footer.subtitle': 'Jikọọ na ndị isi SDP na mpaghara gị. Tinye aka na ọkwa ala.',
    'action.join': 'Sonye',
    'action.donate': 'Nye',
    'action.volunteer': 'Mee Ọrụ Afọ Ofufo',
    'action.search': 'Chọọ',
    'products.badge': 'Ngwaahịa Gọọmentị',
    'products.title': 'Kwado SDP na Ngwaahịa Gọọmentị',
    'products.subtitle': 'Gosi nkwado gị ma nyere aka ịkwado ebumnuche anyị na ngwaahịa SDP dị mma',
    'products.tShirts': 'Uwe T-',
    'products.tShirtsDesc': 'Gosi nkwado gị na uwe T- SDP dị mma. Ejiri akwa dị mma, nke na-adịgide adịgide mee.',
    'products.corporatePackage': 'Ngwugwu Ụlọ Ọrụ',
    'products.corporatePackageDesc': 'Ngwugwu ụlọ ọrụ zuru ezu maka azụmahịa na òtù na-akwado SDP.',
    'products.crest': 'Ihe Ncheta',
    'products.crestDesc': 'Ihe ncheta otu SDP gọọmentị - akara nke ịdị n\'otu, ọganihu, na ntinye aka na ọchịchị dị mma.',
    'products.buyNow': 'Zụta Ugbu A',
    'products.footer': 'Ego niile a na-enweta na-akwado atụmatụ SDP na mkpọsa n\'ofe Naịjirịa',
    'hero.trust.verified': 'Otu Ndọrọndọrọ Emebere',
    'hero.trust.coverage': 'Steeti 36 + Mpaghara FCT',
    'hero.trust.transparent': 'Ọchịchị Na-egosipụta',
    'hero.descriptionText': 'Sonye na Social Democratic Party n\'ịwulite Naịjirịa nke ga-arụ ọrụ maka mmadụ niile - yana',
    'hero.descriptionText2': 'ikpe ziri ezi nke ọha',
    'hero.descriptionText3': 'ezi ọchịchị gọọmentị',
    'hero.descriptionText4': 'na',
    'hero.descriptionText5': 'nsonye ndị ntorobịa',
    'donate.title': 'Nye Onyinye',
    'donate.subtitle': 'Onyinye gị na-akwado mkpọsa anyị maka ọchịchị dị mma na Naịjirịa.',
    'donate.continue': 'Gaa n\'ihu na',
    'donate.step2.title': 'Mechaa Onyinye Gị',
    'donate.step2.amount': 'Ọnụ ego:',
    'donate.form.firstName': 'Aha Mbụ',
    'donate.form.lastName': 'Aha Ikpeazụ',
    'donate.form.email': 'Adreesị Email',
    'donate.form.phone': 'Nọmba Ekwentị',
    'donate.form.otherAmount': 'Ọnụ Ego Ọzọ',
    'donate.form.required': 'chọrọ',
    'donate.form.emailInvalid': 'Achọrọ adreesị email ziri ezi',
    'donate.form.phoneInvalid': 'Achọrọ nọmba ekwentị ziri ezi',
    'donate.form.back': 'Azụ',
    'donate.form.pay': 'Kwụọ ụgwọ',
    'donate.form.processing': 'Na-arụ ọrụ...',
    'donate.form.secure': 'Ịkwụ ụgwọ nchekwa nke Paystack kwadoro',
    'donate.success.title': 'Daalụ!',
    'donate.success.message': 'A nabatala onyinye gị nke ọma.',
    'donate.success.email': 'Ezigala email nkwenye na',
    'donate.success.close': 'Mechie',
    'donate.error.minAmount': 'Ọnụ ego onyinye kacha nta bụ ₦100',
    'donate.error.loading': 'Ọnụ ụzọ ịkwụ ụgwọ na-ebudata. Biko nwaa ọzọ n\'oge na-adịghị anya.',
    'donate.error.failed': 'Ịkwụ ụgwọ dara ada. Biko nwaa ọzọ.',
    'donate.error.closed': 'Emechiela windo ịkwụ ụgwọ. Ọ bụrụ na ịkwụchara ụgwọ, ị ga-enweta email nkwenye.',
    'footer.pastMembers': 'Ndị Otu Gara Agbata',
    'footer.tagline': 'Ịwulite Naịjirịa nke ga-arụ ọrụ maka mmadụ niile - yana ikpe ziri ezi nke ọha, ezi ọchịchị gọọmentị, na nsonye ndị ntorobịa.',
    'footer.quickLinks': 'Njikọ Ngwa Ngwa',
    'footer.getInvolved': 'Sonye',
    'footer.stayUpdated': 'Nọgide Na-amata',
    'footer.subscribe': 'Debanye aha',
    'footer.subscribed': 'Daalụ maka ịdebanye aha!',
    'footer.emailPlaceholder': 'Email gị',
    'footer.copyright': '© 2025 Social Democratic Party (SDP). E nwere ikike niile.',
    'footer.privacy': 'Iwu Nzuzo',
    'footer.terms': 'Usoro Ọrụ',
    'footer.accessibility': 'Ịnweta',
    'footer.joinParty': 'Sonye na Party',
    'footer.findCandidates': 'Chọta Ndị Na-azọ',
    'footer.stateChapters': 'Isi Steeti',
    'wins.category.legislative': 'Iwu',
    'wins.category.agriculture': 'Ọrụ Ugbo',
    'wins.category.humanitarian': 'Onyinye Mmadụ',
    'wins.date.daysAgo': 'ụbọchị gara aga',
    'wins.date.weekAgo': 'izu gara aga',
    'wins.win1.title': 'Senator Wadada Na-ebugharị Mkpụrụ',
    'wins.win1.desc': 'Senator Wadada nwere ihe ịga nke ọma na-ebugharị mkpụrụ maka akụrụngwa ahụike ka mma na mpaghara ime obodo n\'ofe Naịjirịa.',
    'wins.win2.title': 'SDP Nasarawa Na-ekesa Fatịlaịza',
    'wins.win2.desc': 'Isi SDP Nasarawa kesara fatịlaịza n\'efu nye ndị ọrụ ugbo 5,000 iji kwalite mmepụta ọrụ ugbo na nchekwa nri.',
    'wins.win3.title': 'Onye Isi Otu Na-eleta Ogige IDP',
    'wins.win3.desc': 'Onye Isi Otu Prince Adebayo gara ogige IDP na Borno, na-enye ihe enyemaka, olileanya, na ọhụụ maka ọdịnihu.',
    'why.social.desc': 'Ịlụ ọgụ maka nha anya, ikpe ziri ezi, na ikpe ziri ezi maka ndị Naịjirịa niile n\'agbanyeghị nzụlite, agbụrụ, ma ọ bụ ọnọdụ ọha.',
    'why.federalism.desc': 'Inye steeti na gọọmentị ime obodo ike maka ọchịchị ka mma, mmepe, na njikwa akụ.',
    'why.youth.desc': 'Inye ndị ntorobịa Naịjirịa olu na ikpo okwu iji kpụzie ọdịnihu mba anyị site na itinye aka na-arụsi ọrụ ike.',
    'common.loading': 'Na-ebudata...',
    'common.error': 'Njehie',
    'common.success': 'Ihe ịga nke ọma',
    'common.close': 'Mechie',
    'common.cancel': 'Kagbuo',
    'common.save': 'Chekwaa',
    'common.delete': 'Hichapụ',
    'common.edit': 'Dezie',
    'common.submit': 'Ziga',
    'who.title': 'Onye Anyị Bụ',
    'who.subtitle': 'Nhazi Otu & Akụkọ Ihe Mere Eme - Ihe Nketa nke Ọchịchị Onye kwuo Uche',
    'who.about.title': 'Banyere Social Democratic Party',
    'who.about.text1': 'Social Democratic Party nke Naịjirịa (SDP) bụ',
    'who.about.text1Highlight': 'otu ndọrọndọrọ ọchịchị etiti-aka ekpe',
    'who.about.text1Cont': 'na Naịjirịa. E mepụtara ya n\'akụkụ National Republican Convention site n\'aka onye isi ndị agha mbụ Ibrahim Babangida, dị ka akụkụ nke ọrụ ọchịchị onye kwuo uche nke e bu n\'obi ịmepụta otu ndọrọndọrọ ọchịchị mba abụọ – otu dịtụ aka ekpe na nke ọzọ dịtụ aka nri.',
    'who.about.text2': 'N\'oge Republic nke Atọ nke Naịjirịa, a hụrụ ya dị ka',
    'who.about.text2Highlight': 'otu dịtụ nke na-adọrọ ndị ntorobịa nwere ọgụgụ isi na ndị na-akwado ọchịchị onye kwuo uche',
    'who.about.text2Cont': '. Ihe ngosipụta ya na-akwado mbọ ọnụ iji melite ọdịmma na ịlụ ọgụ maka ikpe ziri ezi nke ọha.',
    'who.history.title': 'Akụkọ Ihe Mere Eme Anyị',
    'who.history.subtitle': 'Njem site na Republic nke Atọ ruo ugbu a',
    'who.history.1989': 'Mgbe gọọmentị Ibrahim Babangida machibidoro otu 13 na-atụ anya, ụfọdụ òtù kpebiri ịhazigharị. People\'s Front of Nigeria, People\'s Solidarity Party, na Nigerian Labor Party pụtara iji mepụta isi mpaghara nke SDP ọhụrụ.',
    'who.history.1990': 'A họpụtara Babagana Kingibe onye isi oche otu karịa onye iro ya Mohammed Arzika. N\'agbanyeghị ịchịisi nke ndị Naịjirịa nke Ugwu, ike otu ahụ dị na ndị Igbo na steeti Imo na Anambra.',
    'who.history.1992': 'Otu ahụ meriri',
    'who.history.1992Highlight': '57% nke oche Senate',
    'who.history.1992Cont': 'na',
    'who.history.1992Highlight2': '53% nke oche House of Representatives',
    'who.history.1992Cont2': 'na ntuli aka National Assembly, na-egosipụta ike ntuli aka dị mkpa.',
    'who.history.1993': 'M.K.O. Abiola meriri ntuli aka mbụ na Machị 1993 n\'okpuru usoro Option A4. Abiola zọọrọ ntuli aka mba, nke a machibidoro n\'ụzọ na-adịghị mma site n\'aka Babangida, na-akara oge dị mkpa n\'akụkọ ihe mere eme ọchịchị onye kwuo uche nke Naịjirịa.',
    'who.history.2015': 'Otu ọhụrụ pụtara n\'aha SDP, nke e guzobere site na njikọ nke otu 13. Otu ahụ e weghachiri zọọrọ maka ọkwa na ntuli aka izugbe nke Naịjirịa nke 2015, na-akara mmalite nke nlọghachi SDP na ndọrọndọrọ ọchịchị na-arụsi ọrụ ike.',
    'who.history.2025': 'N\'okpuru nduzi nke Prince Adebayo, SDP na-aga n\'ihu na-enye ndị Naịjirịa nhọrọ ziri ezi, na-edozi mmejọ nke otu ndị ọzọ ma na-enye ikpo okwu maka ọchịchị onye kwuo uche, ezi ọchịchị gọọmentị, na nsonye ndị ntorobịa.',
    'who.structure.title': 'Nhazi Otu',
    'who.structure.subtitle': 'Otu e si guzobe ma hazie SDP',
    'who.structure.formation': 'Ntọala',
    'who.structure.formationDesc': 'E guzobere ya site na njikọ nke People\'s Front of Nigeria, People\'s Solidarity Party, na Nigerian Labor Party mgbe a machibidoro otu 13 na 1989.',
    'who.structure.leadership': 'Nduzi',
    'who.structure.leadershipDesc': 'Nduzi bụkarịrị ndị Naịjirịa nke Ugwu, ebe a họpụtara Babagana Kingibe dị ka onye isi oche otu na 1990. Ike otu ahụ dị na steeti Igbo nke Imo na Anambra.',
    'who.structure.financing': 'Ego',
    'who.structure.financingDesc': 'Otu ahụ bụ ego mbụ site n\'aka gọọmentị Naịjirịa na ndị ọgaranya dị ka Shehu Musa Yar\'Adua, Francis Nzeribe, na M.K.O. Abiola.',
    'who.manifesto.badge': 'Ụkpụrụ Isi',
    'who.manifesto.title': 'Ihe Ngosipụta Mbụ',
    'who.manifesto.subtitle': 'Ụkpụrụ ntọala nke na-eduzi ọhụụ SDP maka Naịjirịa',
    'who.manifesto.energy': 'Ike',
    'who.manifesto.energyDesc': 'Steeti na-ahụ maka ịnye ike maka ebumnuche ụlọ ọrụ na ọha mmadụ.',
    'who.manifesto.rural': 'Mmepe Ime Obodo',
    'who.manifesto.ruralDesc': 'Steeti na-ekwe nkwa ibelata ịda ogbenye ime obodo na njem ime obodo-ime obodo site na nkwado maka òtù obodo na mmepe obodo.',
    'who.manifesto.mining': 'Ngwuputa na Petrochemicals',
    'who.manifesto.miningDesc': 'Steeti ga-ahụ na a na-eji akụ ịnweta nke ọma ma na-achịkwa ya.',
    'who.manifesto.labor': 'Ọrụ, Ọrụ, na Ụgwọ',
    'who.manifesto.laborDesc': 'A ga-anọchite anya ọrụ n\'ihe niile metụtara ndị na-arụ ọrụ.',
    'who.manifesto.education': 'Agụmakwụkwọ',
    'who.manifesto.educationDesc': 'Rụọ ọrụ maka mmemme agụmakwụkwọ n\'efu n\'ọkwa niile.',
    'who.manifesto.defense': 'Nchekwa',
    'who.manifesto.defenseDesc': 'Kwalie ịdabere na onwe, mmepụta mpaghara, na ịtọlite ụlọ ọrụ ngwa agha mpaghara.',
    'who.manifesto.police': 'Ndị Uwe Ojii',
    'who.manifesto.policeDesc': 'Gbanwee àgwà ndị uwe ojii n\'ebe steeti, nghọta nke ọrụ ha, na mmekọrịta ha na ụmụ amaala.',
    'who.revival.title': 'SDP Eweghachiri',
    'who.revival.text1': 'Dị ka Chief Olu Falae si kwuo, e weghachiri SDP iji dozie mmejọ nke otu abụọ a ma ama (People\'s Democratic Party na All Progressive Congress), na inye ndị Naịjirịa nhọrọ ziri ezi, ebe SDP bu ụzọ tupu ma APC na PDP ma nwee akụkọ ihe mere eme nke imeri ntuli aka.',
    'who.revival.text2': 'E guzobere otu ahụ e weghachiri site na njikọ nke otu 13 ma zọọrọ na ntuli aka izugbe nke Naịjirịa nke 2015, na-akara nlọghachi ya na itinye aka na ndọrọndọrọ ọchịchị.',
    'who.platform.title': 'Ikpo Okwu Anyị',
    'who.platform.text1': 'Ikpo okwu SDP na-elekwasị anya n\'inye nhọrọ ziri ezi, ịlụ ọgụ megide nrụrụ aka, na ịmepụta otu ndọrọndọrọ ọchịchị nwere ihe a ga-ewepụta. Otu ahụ na-achọ ijikọ ndị Naịjirịa ma nye olu maka ọchịchọ ha.',
    'who.platform.text2': 'Anyị na-etinye aka n\'imepe oghere ndọrọndọrọ ọchịchị maka ndị ntorobịa Naịjirịa na igosipụta mmetụta nwoke na nwanyị ebe anyị na-akwado ndị nwere nkwarụ.',
    'who.platformObjectives.title': 'Ebumnuche Ikpo Okwu',
    'who.platformObjectives.subtitle': 'Ntinye aka anyị maka ọdịnihu Naịjirịa',
    'who.platformObjectives.democratic': 'Mee Ka Echiche Ọchịchị Onye kwuo Uche Gaa n\'ihu',
    'who.platformObjectives.democraticDesc': 'Mee ka ụkpụrụ na ụkpụrụ ọchịchị onye kwuo uche nke SDP gaa n\'ihu.',
    'who.platformObjectives.thirdPlatform': 'Ikpo Okwu Ndọrọndọrọ Ọchịchị nke Atọ',
    'who.platformObjectives.thirdPlatformDesc': 'Bụrụ ikpo okwu ndọrọndọrọ ọchịchị nke atọ ma dọta ndị ndu ziri ezi, tozuru oke, na ndị siri ike.',
    'who.platformObjectives.corruption': 'Lụọ Ọgụ Megide Nrụrụ Aka',
    'who.platformObjectives.corruptionDesc': 'Lụọ ọgụ megide nrụrụ aka ma weta iwu nke iwu.',
    'who.platformObjectives.patriots': 'Chịkọta Ndị Na-ahụ Mba n\'anya',
    'who.platformObjectives.patriotsDesc': 'Chịkọta ndị na-ahụ mba n\'anya na ndị na-akwado ọchịchị onye kwuo uche ga-anọchite anya ndị mmadụ.',
    'who.platformObjectives.ideological': 'Otu Echiche',
    'who.platformObjectives.ideologicalDesc': 'Mepụtaghachi otu echiche nwere ihe a ga-ewepụta.',
    'who.platformObjectives.national': 'Otu Mba',
    'who.platformObjectives.nationalDesc': 'Mepụta otu mba nwere ọnụnọ n\'ofe steeti niile.',
    'who.platformObjectives.youth': 'Nsonye Ndị Ntorobịa',
    'who.platformObjectives.youthDesc': 'Mepee oghere ndọrọndọrọ ọchịchị maka ndị ntorobịa Naịjirịa.',
    'who.platformObjectives.inclusivity': 'Nsonye',
    'who.platformObjectives.inclusivityDesc': 'Gosipụta mmetụta nwoke na nwanyị ma kwado ndị nwere nkwarụ.',
    'who.platformObjectives.unify': 'Jikọọ Naịjirịa',
    'who.platformObjectives.unifyDesc': 'Jikọọ ndị Naịjirịa ma nye olu na omume maka ọchịchọ na ọchịchọ ha.',
    'who.formerMembers.badge': 'Ndị Gụsịrị Akwụkwọ Pụrụ Iche',
    'who.formerMembers.title': 'Ndị Otu Gara Agbata',
    'who.formerMembers.subtitle': 'SDP abụrụla ebe obibi nye ọtụtụ ndị ndu ndọrọndọrọ ọchịchị pụrụ iche ndị haziri ọnọdụ ndọrọndọrọ ọchịchị Naịjirịa. Ụfọdụ mechara bụrụ ndị isi n\'òtù ndị ọzọ, ebe ndị ọzọ laghachiri na SDP.',
    'who.leadership.title': 'Nhazi Nduzi Ugbu A',
    'who.leadership.subtitle': 'Akụkụ ndị na-eduzi SDP taa',
    'who.leadership.nwc': 'Kọmitii Na-arụ Ọrụ Mba (NWC)',
    'who.leadership.chairman': 'Prince Adebayo',
    'who.leadership.chairmanTitle': 'Onye Isi Oche Mba',
    'who.leadership.chairmanDesc': 'Na-eduzi ọhụụ SDP maka ọchịchị dị mma na mmepe mba.',
    'who.leadership.secretary': 'Odeakwụkwọ',
    'who.leadership.secretaryTitle': 'Odeakwụkwọ Mba',
    'who.leadership.secretaryDesc': 'Na-ahụ maka nchịkwa otu na nhazi.',
    'who.leadership.nwcMembers': 'Ndị Otu NWC',
    'who.leadership.nwcMembersTitle': 'Ndị Otu Kọmitii',
    'who.leadership.nwcMembersDesc': 'Ndị ndu raara onwe ha nye na-arụ ọrụ maka ọganihu Naịjirịa.',
    'who.leadership.senate': 'Ụlọ Nzukọ Senate',
    'who.leadership.senatorWadada': 'Senator Wadada',
    'who.leadership.senatorTitle': 'Senator',
    'who.leadership.senatorWadadaDesc': 'Na-anọchite anya ndị mmadụ ma na-akwado mgbanwe iwu.',
    'who.leadership.senatorAkwashiki': 'Senator Akwashiki',
    'who.leadership.senatorAkwashikiDesc': 'Na-akwado ezi ọchịchị gọọmentị na mmepe ala.',
    'who.leadership.trustees': 'Bọọdụ nke Ndị Ntụkwasị Obi',
    'who.leadership.trusteesDesc': 'Bọọdụ nke Ndị Ntụkwasị Obi anyị nwere ndị okenye na ndị ndu a na-asọpụrụ ndị na-enye nkwụsi ike, ebe nchekwa ụlọ ọrụ, na nduzi nye otu ahụ. Ha na-anọchite anya ọtụtụ afọ ahụmahụ na ndọrọndọrọ ọchịchị na ọchịchị Naịjirịa.',
    'who.constitution.title': 'Iwu Otu',
    'who.constitution.desc': 'Budata Iwu SDP gọọmentị. Akwụkwọ a na-akọwapụta nhazi otu anyị, ụkpụrụ, na usoro ọchịchị. Nkwuwa okwu bụ isi ihe iji wulite ntụkwasị obi.',
    'who.constitution.download': 'Budata Iwu (PDF)',
    'who.viewAchievements': 'Lelee Ihe Ndị E Nwetara',
    'who.expand': 'Mgbasa',
    'who.collapse': 'Mbelata'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('sdp-language') as Language;
    return saved && ['en', 'ha', 'yo', 'ig'].includes(saved) ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('sdp-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

